package com.simpleaccount.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * 高级配色：每套独立浅色/深色方案 + 支出/收入色 + 首页主卡渐变。
 * 用户在「外观」里自选，即时生效。
 */
data class AppPalette(
    val id: String,
    val name: String,
    val tagline: String,
    val swatch: Color,
    val light: ColorScheme,
    val dark: ColorScheme,
    val expense: Color,
    val income: Color,
    val accent: Color,
    val cardGradient: List<Color>,
)

val LocalAppPalette = staticCompositionLocalOf { ColorPalettes.Pine }

object ColorPalettes {
    const val DEFAULT_ID = "pine"

    val Pine = AppPalette(
        id = "pine",
        name = "松绿冷白",
        tagline = "克制、干净，默认",
        swatch = Color(0xFF1F6F5B),
        light = lightColorScheme(
            primary = Color(0xFF1F6F5B),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD7EFE7),
            onPrimaryContainer = Color(0xFF0C3D32),
            secondary = Color(0xFF5B6B73),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE3E8EB),
            onSecondaryContainer = Color(0xFF243038),
            tertiary = Color(0xFF2A9D6E),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD4F3E4),
            onTertiaryContainer = Color(0xFF0D3B28),
            background = Color(0xFFF4F6F8),
            onBackground = Color(0xFF1A1F22),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF1A1F22),
            surfaceVariant = Color(0xFFEAEEF1),
            onSurfaceVariant = Color(0xFF5A646A),
            outline = Color(0xFFD5DCE1),
            outlineVariant = Color(0xFFE8EDF0),
            error = Color(0xFFD4523E),
            onError = Color.White,
            errorContainer = Color(0xFFF8D8D3),
            onErrorContainer = Color(0xFF4A1C16),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF7DCFB6),
            onPrimary = Color(0xFF07382C),
            primaryContainer = Color(0xFF1A4A3E),
            onPrimaryContainer = Color(0xFFD7EFE7),
            secondary = Color(0xFFB7C2C8),
            onSecondary = Color(0xFF1C2428),
            secondaryContainer = Color(0xFF2A3338),
            onSecondaryContainer = Color(0xFFE3E8EB),
            tertiary = Color(0xFF7ED9AE),
            onTertiary = Color(0xFF0C241C),
            tertiaryContainer = Color(0xFF1E3D32),
            onTertiaryContainer = Color(0xFFD4F3E4),
            background = Color(0xFF101416),
            onBackground = Color(0xFFE6EBEE),
            surface = Color(0xFF181C1F),
            onSurface = Color(0xFFE6EBEE),
            surfaceVariant = Color(0xFF242A2E),
            onSurfaceVariant = Color(0xFFA8B2B8),
            outline = Color(0xFF3A4248),
            outlineVariant = Color(0xFF2A3136),
            error = Color(0xFFE08B7E),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2A24),
            onErrorContainer = Color(0xFFF6D6D1),
        ),
        expense = Color(0xFFD4523E),
        income = Color(0xFF2A9D6E),
        accent = Color(0xFFE8A87C),
        cardGradient = listOf(Color(0xFF1A4A3E), Color(0xFF1F6F5B), Color(0xFF165A4A)),
    )

    val Ink = AppPalette(
        id = "ink",
        name = "墨兰夜雪",
        tagline = "靛蓝纸白，沉静",
        swatch = Color(0xFF2C4A6E),
        light = lightColorScheme(
            primary = Color(0xFF2C4A6E),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD9E4F0),
            onPrimaryContainer = Color(0xFF12243A),
            secondary = Color(0xFF5C6770),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE4E8EC),
            onSecondaryContainer = Color(0xFF232A30),
            tertiary = Color(0xFF3D7A8C),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD4EAF0),
            onTertiaryContainer = Color(0xFF12323A),
            background = Color(0xFFF3F5F8),
            onBackground = Color(0xFF171C22),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF171C22),
            surfaceVariant = Color(0xFFE6EBF1),
            onSurfaceVariant = Color(0xFF566070),
            outline = Color(0xFFD0D7E0),
            outlineVariant = Color(0xFFE8EDF3),
            error = Color(0xFFC45C4A),
            onError = Color.White,
            errorContainer = Color(0xFFF6D8D2),
            onErrorContainer = Color(0xFF4A1C16),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF9BB6D4),
            onPrimary = Color(0xFF102033),
            primaryContainer = Color(0xFF1C334D),
            onPrimaryContainer = Color(0xFFD9E4F0),
            secondary = Color(0xFFB8C2CC),
            onSecondary = Color(0xFF1A2026),
            secondaryContainer = Color(0xFF2A323A),
            onSecondaryContainer = Color(0xFFE4E8EC),
            tertiary = Color(0xFF8FCBD8),
            onTertiary = Color(0xFF0E2A32),
            tertiaryContainer = Color(0xFF1E3A44),
            onTertiaryContainer = Color(0xFFD4EAF0),
            background = Color(0xFF0E1218),
            onBackground = Color(0xFFE4EAF0),
            surface = Color(0xFF161B22),
            onSurface = Color(0xFFE4EAF0),
            surfaceVariant = Color(0xFF222A33),
            onSurfaceVariant = Color(0xFFA8B4C0),
            outline = Color(0xFF38424C),
            outlineVariant = Color(0xFF272F38),
            error = Color(0xFFE09A8E),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2A24),
            onErrorContainer = Color(0xFFF6D6D1),
        ),
        expense = Color(0xFFC45C4A),
        income = Color(0xFF3D7A8C),
        accent = Color(0xFFC4A882),
        cardGradient = listOf(Color(0xFF1A2E48), Color(0xFF2C4A6E), Color(0xFF1E3A58)),
    )

    val Mist = AppPalette(
        id = "mist",
        name = "紫雾香槟",
        tagline = "雾紫配浅金，安静",
        swatch = Color(0xFF6B5B7A),
        light = lightColorScheme(
            primary = Color(0xFF6B5B7A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFE8E0F0),
            onPrimaryContainer = Color(0xFF2C2438),
            secondary = Color(0xFF6A635C),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFECE8E2),
            onSecondaryContainer = Color(0xFF2C2824),
            tertiary = Color(0xFF8A6E4A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF3E6D4),
            onTertiaryContainer = Color(0xFF3A2C18),
            background = Color(0xFFF7F4F1),
            onBackground = Color(0xFF1E1A1C),
            surface = Color(0xFFFFFCF9),
            onSurface = Color(0xFF1E1A1C),
            surfaceVariant = Color(0xFFEFE8F0),
            onSurfaceVariant = Color(0xFF655E68),
            outline = Color(0xFFDCD4DC),
            outlineVariant = Color(0xFFF0EAE8),
            error = Color(0xFFB85C5C),
            onError = Color.White,
            errorContainer = Color(0xFFF5D6D6),
            onErrorContainer = Color(0xFF4A1C1C),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFC4B4D4),
            onPrimary = Color(0xFF2A2034),
            primaryContainer = Color(0xFF3E334C),
            onPrimaryContainer = Color(0xFFE8E0F0),
            secondary = Color(0xFFC8C0B6),
            onSecondary = Color(0xFF26221E),
            secondaryContainer = Color(0xFF3A342E),
            onSecondaryContainer = Color(0xFFECE8E2),
            tertiary = Color(0xFFD4B896),
            onTertiary = Color(0xFF2E2414),
            tertiaryContainer = Color(0xFF443628),
            onTertiaryContainer = Color(0xFFF3E6D4),
            background = Color(0xFF141216),
            onBackground = Color(0xFFECE6EC),
            surface = Color(0xFF1C191E),
            onSurface = Color(0xFFECE6EC),
            surfaceVariant = Color(0xFF2A252C),
            onSurfaceVariant = Color(0xFFB8B0B8),
            outline = Color(0xFF423A44),
            outlineVariant = Color(0xFF2E282E),
            error = Color(0xFFE0A0A0),
            onError = Color(0xFF3A1414),
            errorContainer = Color(0xFF5C2A2A),
            onErrorContainer = Color(0xFFF5D6D6),
        ),
        expense = Color(0xFFB85C5C),
        income = Color(0xFF5A8A72),
        accent = Color(0xFFC4A882),
        cardGradient = listOf(Color(0xFF3E334C), Color(0xFF6B5B7A), Color(0xFF4A3E58)),
    )

    val Terra = AppPalette(
        id = "terra",
        name = "赤陶暖沙",
        tagline = "陶土与米纸",
        swatch = Color(0xFFB56A4A),
        light = lightColorScheme(
            primary = Color(0xFFB56A4A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF4E0D4),
            onPrimaryContainer = Color(0xFF3A2216),
            secondary = Color(0xFF6E645C),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFECE6E0),
            onSecondaryContainer = Color(0xFF2C2622),
            tertiary = Color(0xFF6A8A62),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFDCE8D6),
            onTertiaryContainer = Color(0xFF24301E),
            background = Color(0xFFF7F2EC),
            onBackground = Color(0xFF221C18),
            surface = Color(0xFFFFFBF6),
            onSurface = Color(0xFF221C18),
            surfaceVariant = Color(0xFFF0E6DC),
            onSurfaceVariant = Color(0xFF6A6058),
            outline = Color(0xFFE0D4C8),
            outlineVariant = Color(0xFFF4EBE2),
            error = Color(0xFFC44A3A),
            onError = Color.White,
            errorContainer = Color(0xFFF6D4CE),
            onErrorContainer = Color(0xFF4A1C16),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFE0B098),
            onPrimary = Color(0xFF3A2216),
            primaryContainer = Color(0xFF5C3A2C),
            onPrimaryContainer = Color(0xFFF4E0D4),
            secondary = Color(0xFFC8C0B8),
            onSecondary = Color(0xFF24201C),
            secondaryContainer = Color(0xFF3A342E),
            onSecondaryContainer = Color(0xFFECE6E0),
            tertiary = Color(0xFFA8C49E),
            onTertiary = Color(0xFF1C2818),
            tertiaryContainer = Color(0xFF34402E),
            onTertiaryContainer = Color(0xFFDCE8D6),
            background = Color(0xFF161210),
            onBackground = Color(0xFFF0E8E0),
            surface = Color(0xFF1E1A16),
            onSurface = Color(0xFFF0E8E0),
            surfaceVariant = Color(0xFF2C2622),
            onSurfaceVariant = Color(0xFFB8AEA4),
            outline = Color(0xFF443C36),
            outlineVariant = Color(0xFF302A26),
            error = Color(0xFFE08A7A),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2A24),
            onErrorContainer = Color(0xFFF6D4CE),
        ),
        expense = Color(0xFFC44A3A),
        income = Color(0xFF6A8A62),
        accent = Color(0xFFD4B896),
        cardGradient = listOf(Color(0xFF6A3E2C), Color(0xFFB56A4A), Color(0xFF8A4E36)),
    )

    val Graphite = AppPalette(
        id = "graphite",
        name = "石墨青灰",
        tagline = "冷灰石青",
        swatch = Color(0xFF3D5A5A),
        light = lightColorScheme(
            primary = Color(0xFF3D5A5A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD4E4E4),
            onPrimaryContainer = Color(0xFF142424),
            secondary = Color(0xFF5C6468),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE4E8EA),
            onSecondaryContainer = Color(0xFF24282A),
            tertiary = Color(0xFF4A7A6A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD4E8E0),
            onTertiaryContainer = Color(0xFF1A3028),
            background = Color(0xFFF2F4F4),
            onBackground = Color(0xFF181C1C),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF181C1C),
            surfaceVariant = Color(0xFFE4EAE8),
            onSurfaceVariant = Color(0xFF586260),
            outline = Color(0xFFD0D8D6),
            outlineVariant = Color(0xFFE8EEEC),
            error = Color(0xFFC45A4A),
            onError = Color.White,
            errorContainer = Color(0xFFF4D6D0),
            onErrorContainer = Color(0xFF4A1C16),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF9CBCB8),
            onPrimary = Color(0xFF142424),
            primaryContainer = Color(0xFF2A4040),
            onPrimaryContainer = Color(0xFFD4E4E4),
            secondary = Color(0xFFB8C0C4),
            onSecondary = Color(0xFF1C2022),
            secondaryContainer = Color(0xFF2C3234),
            onSecondaryContainer = Color(0xFFE4E8EA),
            tertiary = Color(0xFF9CC8B8),
            onTertiary = Color(0xFF14241E),
            tertiaryContainer = Color(0xFF2A4038),
            onTertiaryContainer = Color(0xFFD4E8E0),
            background = Color(0xFF101414),
            onBackground = Color(0xFFE4EAEA),
            surface = Color(0xFF181C1C),
            onSurface = Color(0xFFE4EAEA),
            surfaceVariant = Color(0xFF242A2A),
            onSurfaceVariant = Color(0xFFA8B2B0),
            outline = Color(0xFF3A4242),
            outlineVariant = Color(0xFF2A3030),
            error = Color(0xFFE09A8E),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2A24),
            onErrorContainer = Color(0xFFF4D6D0),
        ),
        expense = Color(0xFFC45A4A),
        income = Color(0xFF4A7A6A),
        accent = Color(0xFFC4B496),
        cardGradient = listOf(Color(0xFF243838), Color(0xFF3D5A5A), Color(0xFF2E4848)),
    )

    val Moon = AppPalette(
        id = "moon",
        name = "月白玄青",
        tagline = "月白纸面，玄青字",
        swatch = Color(0xFF1E4A5A),
        light = lightColorScheme(
            primary = Color(0xFF1E4A5A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD2E6EE),
            onPrimaryContainer = Color(0xFF0C2832),
            secondary = Color(0xFF5A646C),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE2E8EC),
            onSecondaryContainer = Color(0xFF222830),
            tertiary = Color(0xFF2E7A6A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD2EEE6),
            onTertiaryContainer = Color(0xFF0E3028),
            background = Color(0xFFF5F7F8),
            onBackground = Color(0xFF161C20),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF161C20),
            surfaceVariant = Color(0xFFE6EEF0),
            onSurfaceVariant = Color(0xFF546068),
            outline = Color(0xFFD0DCE0),
            outlineVariant = Color(0xFFE8F0F2),
            error = Color(0xFFC05048),
            onError = Color.White,
            errorContainer = Color(0xFFF4D4D0),
            onErrorContainer = Color(0xFF4A1816),
        ),
        dark = darkColorScheme(
            primary = Color(0xFF8EC4D4),
            onPrimary = Color(0xFF0C2832),
            primaryContainer = Color(0xFF163844),
            onPrimaryContainer = Color(0xFFD2E6EE),
            secondary = Color(0xFFB4C0C8),
            onSecondary = Color(0xFF1A2024),
            secondaryContainer = Color(0xFF2A3238),
            onSecondaryContainer = Color(0xFFE2E8EC),
            tertiary = Color(0xFF8ED0C0),
            onTertiary = Color(0xFF0C2822),
            tertiaryContainer = Color(0xFF1E3C36),
            onTertiaryContainer = Color(0xFFD2EEE6),
            background = Color(0xFF0C1216),
            onBackground = Color(0xFFE2ECF0),
            surface = Color(0xFF141A1E),
            onSurface = Color(0xFFE2ECF0),
            surfaceVariant = Color(0xFF20282C),
            onSurfaceVariant = Color(0xFFA4B4BC),
            outline = Color(0xFF364048),
            outlineVariant = Color(0xFF262E32),
            error = Color(0xFFE09088),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2824),
            onErrorContainer = Color(0xFFF4D4D0),
        ),
        expense = Color(0xFFC05048),
        income = Color(0xFF2E7A6A),
        accent = Color(0xFFD2B48A),
        cardGradient = listOf(Color(0xFF143844), Color(0xFF1E4A5A), Color(0xFF163E4C)),
    )

    val Cinnabar = AppPalette(
        id = "cinnabar",
        name = "绛红米纸",
        tagline = "朱砂点在米纸上",
        swatch = Color(0xFF8C3A3A),
        light = lightColorScheme(
            primary = Color(0xFF8C3A3A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFF4DCDC),
            onPrimaryContainer = Color(0xFF3A1616),
            secondary = Color(0xFF6A6058),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFECE6E0),
            onSecondaryContainer = Color(0xFF2C2622),
            tertiary = Color(0xFF5A7A5A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFDCE8DC),
            onTertiaryContainer = Color(0xFF1E2C1E),
            background = Color(0xFFF8F4F0),
            onBackground = Color(0xFF221816),
            surface = Color(0xFFFFFCF8),
            onSurface = Color(0xFF221816),
            surfaceVariant = Color(0xFFF0E6E4),
            onSurfaceVariant = Color(0xFF6A5858),
            outline = Color(0xFFE0D4D0),
            outlineVariant = Color(0xFFF4EAE8),
            error = Color(0xFFB03030),
            onError = Color.White,
            errorContainer = Color(0xFFF4D0D0),
            onErrorContainer = Color(0xFF4A1414),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFE0A8A8),
            onPrimary = Color(0xFF3A1616),
            primaryContainer = Color(0xFF5C2A2A),
            onPrimaryContainer = Color(0xFFF4DCDC),
            secondary = Color(0xFFC8C0B8),
            onSecondary = Color(0xFF24201C),
            secondaryContainer = Color(0xFF3A342E),
            onSecondaryContainer = Color(0xFFECE6E0),
            tertiary = Color(0xFFA8C4A8),
            onTertiary = Color(0xFF1A281A),
            tertiaryContainer = Color(0xFF2E3C2E),
            onTertiaryContainer = Color(0xFFDCE8DC),
            background = Color(0xFF161210),
            onBackground = Color(0xFFF0E6E4),
            surface = Color(0xFF1E1816),
            onSurface = Color(0xFFF0E6E4),
            surfaceVariant = Color(0xFF2C2422),
            onSurfaceVariant = Color(0xFFB8A8A6),
            outline = Color(0xFF443836),
            outlineVariant = Color(0xFF302826),
            error = Color(0xFFE09090),
            onError = Color(0xFF3A1414),
            errorContainer = Color(0xFF5C2424),
            onErrorContainer = Color(0xFFF4D0D0),
        ),
        expense = Color(0xFFB03030),
        income = Color(0xFF5A7A5A),
        accent = Color(0xFFD4B48A),
        cardGradient = listOf(Color(0xFF5C2428), Color(0xFF8C3A3A), Color(0xFF6A2C2C)),
    )

    val Salt = AppPalette(
        id = "salt",
        name = "海盐雾蓝",
        tagline = "浅盐蓝，清爽",
        swatch = Color(0xFF4A6E8A),
        light = lightColorScheme(
            primary = Color(0xFF4A6E8A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD6E4F0),
            onPrimaryContainer = Color(0xFF1A2C3A),
            secondary = Color(0xFF5C686E),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE4E8EC),
            onSecondaryContainer = Color(0xFF242A2E),
            tertiary = Color(0xFF3A8A7A),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFD2EEE6),
            onTertiaryContainer = Color(0xFF12322C),
            background = Color(0xFFF4F6F8),
            onBackground = Color(0xFF181C20),
            surface = Color(0xFFFFFFFF),
            onSurface = Color(0xFF181C20),
            surfaceVariant = Color(0xFFE6EEF2),
            onSurfaceVariant = Color(0xFF546068),
            outline = Color(0xFFD0D8E0),
            outlineVariant = Color(0xFFE8EEF2),
            error = Color(0xFFC45C4C),
            onError = Color.White,
            errorContainer = Color(0xFFF4D6D0),
            onErrorContainer = Color(0xFF4A1C16),
        ),
        dark = darkColorScheme(
            primary = Color(0xFFA8C4D8),
            onPrimary = Color(0xFF1A2C3A),
            primaryContainer = Color(0xFF2E4A60),
            onPrimaryContainer = Color(0xFFD6E4F0),
            secondary = Color(0xFFB8C4CC),
            onSecondary = Color(0xFF1C2226),
            secondaryContainer = Color(0xFF2C3438),
            onSecondaryContainer = Color(0xFFE4E8EC),
            tertiary = Color(0xFF90D0C0),
            onTertiary = Color(0xFF0E2822),
            tertiaryContainer = Color(0xFF1E3C36),
            onTertiaryContainer = Color(0xFFD2EEE6),
            background = Color(0xFF101418),
            onBackground = Color(0xFFE4ECF0),
            surface = Color(0xFF181C20),
            onSurface = Color(0xFFE4ECF0),
            surfaceVariant = Color(0xFF242C32),
            onSurfaceVariant = Color(0xFFA8B6C0),
            outline = Color(0xFF384048),
            outlineVariant = Color(0xFF282E34),
            error = Color(0xFFE09A8E),
            onError = Color(0xFF3A1410),
            errorContainer = Color(0xFF5C2A24),
            onErrorContainer = Color(0xFFF4D6D0),
        ),
        expense = Color(0xFFC45C4C),
        income = Color(0xFF3A8A7A),
        accent = Color(0xFFC4B090),
        cardGradient = listOf(Color(0xFF2E4A60), Color(0xFF4A6E8A), Color(0xFF3A5A74)),
    )

    val all: List<AppPalette> = listOf(Pine, Ink, Mist, Terra, Graphite, Moon, Cinnabar, Salt)

    fun byId(id: String?): AppPalette = all.firstOrNull { it.id == id } ?: Pine
}
